name: 'Deploy to Azure Container Instances'
description: 'Deploy to Containers to Azure Container Instances. github.com/Azure/Actions'
inputs:
    resource-group:
        description: 'Name of the Resource Group in which the Container Instance will be created'
        required: true
    location:
        description: 'Location where the Container will be deployed'
        required: true
    name:
        description: 'Name of the Container Group Instance'
        required: true
    subscription-id:
        description: 'Name of the Subscription ID'
        required: true
outputs:
    app-url:
        description: 'URL of the Deployed Application'
branding:
    icon: 'azure-logo.svg'
    color: 'blue'
runs:
    using: 'node12'
    main: 'lib/main.js'
