on: [push]
name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0' # Need to specify the miner version
        registry-url: 'https://npm.pkg.github.com'

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Container Apps'
      uses: "yuhattor/aca-deploy@main"
      with:
        resource-group: sample-rg
        name: yuhattor-container
        location: 'east us'
        subscription-id: 'a4deccb1-a1f6-40cb-a923-f55a7d22c32d'