on: [push]
name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
      
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm install
    - run: npm ls --depth=0
    - name: 'Install npm packages'
      run: npm install

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Container Apps'
      uses: "yuhattor/aca-deploy@main"
      with:
        resource-group: sample-rg
        name: yuhattor-container
        location: 'east us'
        subscription-id: 'a4deccb1-a1f6-40cb-a923-f55a7d22c32d'